Implemented presentor and views for bootstrap and md
P-RCollaboration/CoreComponents pull request #9
Opened 2021-03-09 10:39 UTC by bpasha7

2021-03-10 06:13 UTC, trueromanus requested changes
Need few changes

2021-03-12 10:25 UTC, bpasha7 commented on src/views/bootstrap/ListGroupView.vue
> +<template>
renamed to ListBox

2021-03-12 10:26 UTC, bpasha7 commented on src/examples/helloworld/App.vue
> +                                {{item}}
done=)

2021-03-12 10:27 UTC, bpasha7 commented on src/states/ListGroupState.vue
> +    }
We have decided to implement ListBox logic

2021-03-12 14:46 UTC, trueromanus approved these changes
done

2021-03-15 11:41 UTC, merged